### ISSUE TITLE
How does it works!?

### ISSUE THREAD

**Issue by marcelopetersen** [Statyk7/log2console#3]
Hello,

The idea seems great, but after installed the project, I couldn't understand how it works.
I've set a receiver to a flat file, but nothing happens !!!

Could you provide more details about how to use it?

Thank you

**Comment by Statyk7** [comment]
Hi,

When used with a flat file the tool will display the content of the file each time the file is updated, according it is open with conccurent read.

Otherwise the best usage of the tool is with a logging framework like Log4net, using the Remoting Appender, there is a sample configuration when you select this appender type in the settings.

Remy
